// lang-de.js
export const questAnswersDE = {
  qc: [
    { id: 1, answer: "Kein Problem." },
    { id: 2, answer: "Ich kann nicht." },
    { id: 3, answer: "Ich bin richtig müde." },
    { id: 4, answer: "Ich mach Spaß." },
    { id: 5, answer: "Ich bin." },
    { id: 6, answer: "Also hör zu." },
    { id: 7, answer: "Also hör zu." },
    { id: 8, answer: "Und ..." },
    { id: 9, answer: "Also / das bedeutet" },
    { id: 10, answer: "Und mehr / außerdem." },
  ],
  home: [
    { id: 1, answer: "Möchtest du etwas trinken?" },
    { id: 2, answer: "Gib mir bitte die Butter." },
    { id: 3, answer: "Wo ist die Toilette, bitte?" },
    { id: 4, answer: "Kannst du bitte die Tür schließen?" },
    { id: 5, answer: "Reichst du mir bitte das Salz?" },
    { id: 6, answer: "Hast du Hunger? Lass uns essen!" },
    { id: 7, answer: "Gib mir bitte einen Kaffee." },
    { id: 8, answer: "Möchtest du einen kleinen Snack?" },
    { id: 9, answer: "Mach bitte das Licht aus." },
    { id: 10, answer: "Mach bitte den Fernseher an." },
    { id: 11, answer: "Reich mir bitte den Stuhl." },
    { id: 12, answer: "Schließ bitte das Fenster." },
    { id: 13, answer: "Reinige bitte den Tisch." },
    { id: 14, answer: "Möchtest du ein Stück Kuchen?" },
    { id: 15, answer: "Reich mir bitte einen Teller." },
    { id: 16, answer: "Reich mir bitte das Brot." },
    { id: 17, answer: "Kannst du mir beim Abwasch helfen?" },
    { id: 18, answer: "Möchtest du einen Film sehen?" },
    { id: 19, answer: "Räume bitte dein Zimmer auf." },
    { id: 20, answer: "Nimm deinen Mantel, es ist kalt draußen." },
    { id: 21, answer: "Beeil dich bitte." },
    { id: 22, answer: "Möchtest du eine kurze Pause machen?" },
    { id: 23, answer: "Vertrau mir bitte." },
    { id: 24, answer: "Leg dich bitte einen Moment hin." },
    { id: 25, answer: "Kommst du, um mir in der Küche zu helfen?" },
    { id: 26, answer: "Erinnere mich, die Tür zu schließen." },
    { id: 27, answer: "Pass bitte auf." },
    { id: 28, answer: "Möchtest du einen heißen Kaffee?" },
    { id: 29, answer: "Nimm deinen Regenschirm, es wird regnen." },
    { id: 30, answer: "Sag mir bitte die Wahrheit." },
  ],
  med: [
    { id: 1, answer: "Wie geht es Ihnen heute?" },
    { id: 2, answer: "Haben Sie in der Nacht Schmerzen verspürt?" },
    { id: 3, answer: "Wo haben Sie Schmerzen?" },
    { id: 4, answer: "Nehmen Sie Medikamente ein?" },
    { id: 5, answer: "Seit wann haben Sie diese Symptome?" },
    { id: 6, answer: "Haben Sie Fieber?" },
    { id: 7, answer: "Haben Sie Allergien?" },
    { id: 8, answer: "Treiben Sie regelmäßig Sport?" },
    { id: 9, answer: "Haben Sie gut geschlafen?" },
    { id: 10, answer: "Leiden Sie unter Bluthochdruck?" },
    { id: 11, answer: "Wann war Ihr letzter Arzttermin?" },
    { id: 12, answer: "Hatten Sie schon einmal eine Operation?" },
    { id: 13, answer: "Können Sie Ihre Schmerzen beschreiben?" },
    { id: 14, answer: "Wie gehen Sie mit Stress um?" },
    { id: 15, answer: "Haben Sie eine Krankenversicherung?" },
    { id: 16, answer: "Haben Sie in letzter Zeit Schwindelgefühle gehabt?" },
    { id: 17, answer: "Sind Sie schwanger?" },
    { id: 18, answer: "Rauchen Sie?" },
    { id: 19, answer: "Wie viele Zigaretten rauchen Sie pro Tag?" },
    { id: 20, answer: "Sind Sie nüchtern?" },
    { id: 21, answer: "Wann war Ihre letzte Blutuntersuchung?" },
    { id: 22, answer: "Hatten Sie schon einmal einen Herzinfarkt?" },
    { id: 23, answer: "Nehmen Sie Vitaminpräparate ein?" },
    { id: 24, answer: "Gibt es in Ihrer Familie Fälle von Diabetes?" },
    { id: 25, answer: "Haben Sie Brustschmerzen?" },
    { id: 26, answer: "Haben Sie Atembeschwerden?" },
    { id: 27, answer: "Seit wann haben Sie diese Schmerzen?" },
    { id: 28, answer: "Wie schätzen Sie Ihr Müdigkeitslevel ein?" },
    { id: 29, answer: "Leiden Sie an Schlaflosigkeit?" },
    { id: 30, answer: "Haben Sie eine Veränderung Ihres Appetits bemerkt?" },
  ],
  feel: [
    { id: 1, answer: "Mir geht es wunderbar." },
    { id: 2, answer: "Bist du glücklich?" },
    { id: 3, answer: "Ist dir das schöne Wetter aufgefallen?" },
    { id: 4, answer: "Warum schmollst du seit heute Morgen?" },
    { id: 5, answer: "Ich habe dich letzte Nacht vermisst." },
    { id: 6, answer: "Möchtest du dieses Wochenende ausgehen?" },
    { id: 7, answer: "Du siehst nicht gut aus. Ist alles in Ordnung?" },
    { id: 8, answer: "Denkst du immer noch an deinen Ex?" },
    { id: 9, answer: "Hey, möchtest du eine Umarmung?" },
    { id: 10, answer: "Passiert es dir jemals, dass du grundlos weinst?" },
    { id: 11, answer: "Findest du nicht, dass das Leben heute schön ist?" },
    { id: 12, answer: "Möchtest du darüber sprechen, was dich belastet?" },
    { id: 13, answer: "Warum wirst du so schüchtern, wenn wir über die Liebe sprechen?" },
    { id: 14, answer: "Sollen wir heute Abend essen gehen?" },
    { id: 15, answer: "Glaubst du an Liebe auf den ersten Blick?" },
    { id: 16, answer: "Wie gehst du normalerweise mit Wut um?" },
    { id: 17, answer: "Ich habe Angst, das Leben zu verpassen. Geht es dir nicht genauso?" },
    { id: 18, answer: "Möchtest du mit mir einen Kaffee trinken?" },
    { id: 19, answer: "Hast du jemals diese tiefe innere Leere gespürt?" },
    { id: 20, answer: "Hast du in letzter Zeit gut geschlafen?" },
    { id: 21, answer: "Hast du jemals darüber nachgedacht, einfach wegzulaufen und alles hinter dir zu lassen?" },
    { id: 22, answer: "Ist es nicht ermüdend, überall gleichzeitig zu sein?" },
    { id: 23, answer: "Bist du eifersüchtiger?" },
    { id: 24, answer: "Warum hast du gestern so viel geschrien?" },
    { id: 25, answer: "Was hast du für deinen Urlaub geplant?" },
    { id: 26, answer: "Welche Art von Musik hörst du, wenn du traurig bist?" },
    { id: 27, answer: "Möchtest du einen Film-Marathon mit mir machen?" },
    { id: 28, answer: "Was ist dein schlimmster Albtraum?" },
    { id: 29, answer: "Glaubst du, dass alles aus einem bestimmten Grund geschieht?" },
    { id: 30, answer: "Also, was macht dich wirklich glücklich?" },
  ],
  
  act: [
    { id: 1, answer: "Ich handel korrekt." },
    { id: 2, answer: "Ich wette, dass du gewinnst."},
    { id: 3, answer: "Ich wette, dass ich verliere"},
    { id: 4, answer: "Ich bin gerade dabei, zu kochen"},
    { id: 5, answer: "Ich komme!"},
    { id: 6, answer: "Ich komme um 3 Uhr."},
    { id: 7, answer: "Ich komme am Montag wieder."},
    { id: 8, answer: "Ich koche gerade."},
    { id: 9, answer: "Ich habe gerade gekocht."},
    { id: 10, answer: "Ich bin gerade angekommen."},
    { id: 11, answer: "Ich verstehe das."},
    { id: 12, answer: "Ich verstehe das nicht."},
    { id: 13, answer: "Ich fahre zu dir."},
    { id: 14, answer: "Ich gehe spazieren."},
    { id: 15, answer: "Ich warte auf dich."},
    { id: 16, answer: "Ich habe genug."},
    { id: 17, answer: "Ich gehe schwimmen."},
    { id: 18, answer: "Ich schwimme im Pool."},
    { id: 19, answer: "Ich sitze in der Küche."},
    { id: 20, answer: "Ich habe recht."},
    { id: 21, answer: "Ich habe mich geirrt."},
    { id: 22, answer: "Ich habe mich verirrt."},
    { id: 23, answer: "Ich gehe den Hügel hinauf"},
    { id: 24, answer: "Ich gehe den Hügel hinab."},
    { id: 25, answer: "Ich ins Auto."},
    { id: 26, answer: "Ich steige aufs Fahrrad."},
    { id: 27, answer: "Ich sage es nur einmal."},
    { id: 28, answer: "Ich mag diese Idee."},
    { id: 29, answer: "Ich bin nicht deiner Meinung."},
    { id: 30, answer: "Ich mache jetzt Schluss."},
  ],
};


