// lang-de.js
export const questAnswersDE = {
  qc: [
    { id: 1, answer: "Kein Problem." },
    { id: 2, answer: "Ich kann nicht." },
    { id: 3, answer: "Ich bin richtig müde." },
    { id: 4, answer: "Ich mach Spaß." },
    { id: 5, answer: "Ich bin." },
    { id: 6, answer: "Also hör zu." },
    { id: 7, answer: "Also hör zu." },
    { id: 8, answer: "Und ..." },
    { id: 9, answer: "Also / das bedeutet" },
    { id: 10, answer: "Und mehr / außerdem." },
  ],
  home: [
    { id: 1, answer: "Möchtest du etwas trinken?" },
    { id: 2, answer: "Gib mir bitte die Butter." },
    { id: 3, answer: "Wo ist die Toilette, bitte?" },
    { id: 4, answer: "Kannst du bitte die Tür schließen?" },
    { id: 5, answer: "Reichst du mir bitte das Salz?" },
    { id: 6, answer: "Hast du Hunger? Lass uns essen!" },
    { id: 7, answer: "Gib mir bitte einen Kaffee." },
    { id: 8, answer: "Möchtest du einen kleinen Snack?" },
    { id: 9, answer: "Mach bitte das Licht aus." },
    { id: 10, answer: "Mach bitte den Fernseher an." },
    { id: 11, answer: "Reich mir bitte den Stuhl." },
    { id: 12, answer: "Schließ bitte das Fenster." },
    { id: 13, answer: "Reinige bitte den Tisch." },
    { id: 14, answer: "Möchtest du ein Stück Kuchen?" },
    { id: 15, answer: "Reich mir bitte einen Teller." },
    { id: 16, answer: "Reich mir bitte das Brot." },
    { id: 17, answer: "Kannst du mir beim Abwasch helfen?" },
    { id: 18, answer: "Möchtest du einen Film sehen?" },
    { id: 19, answer: "Räume bitte dein Zimmer auf." },
    { id: 20, answer: "Nimm deinen Mantel, es ist kalt draußen." },
    { id: 21, answer: "Beeil dich bitte." },
    { id: 22, answer: "Möchtest du eine kurze Pause machen?" },
    { id: 23, answer: "Vertrau mir bitte." },
    { id: 24, answer: "Leg dich bitte einen Moment hin." },
    { id: 25, answer: "Kommst du, um mir in der Küche zu helfen?" },
    { id: 26, answer: "Erinnere mich, die Tür zu schließen." },
    { id: 27, answer: "Pass bitte auf." },
    { id: 28, answer: "Möchtest du einen heißen Kaffee?" },
    { id: 29, answer: "Nimm deinen Regenschirm, es wird regnen." },
    { id: 30, answer: "Sag mir bitte die Wahrheit." },
  ],
  med: [
    { id: 1, answer: "Wie geht es Ihnen heute?" },
    { id: 2, answer: "Haben Sie in der Nacht Schmerzen verspürt?" },
    { id: 3, answer: "Wo haben Sie Schmerzen?" },
    { id: 4, answer: "Nehmen Sie Medikamente ein?" },
    { id: 5, answer: "Seit wann haben Sie diese Symptome?" },
    { id: 6, answer: "Haben Sie Fieber?" },
    { id: 7, answer: "Haben Sie Allergien?" },
    { id: 8, answer: "Treiben Sie regelmäßig Sport?" },
    { id: 9, answer: "Haben Sie gut geschlafen?" },
    { id: 10, answer: "Leiden Sie unter Bluthochdruck?" },
    { id: 11, answer: "Wann war Ihr letzter Arzttermin?" },
    { id: 12, answer: "Hatten Sie schon einmal eine Operation?" },
    { id: 13, answer: "Können Sie Ihre Schmerzen beschreiben?" },
    { id: 14, answer: "Wie gehen Sie mit Stress um?" },
    { id: 15, answer: "Haben Sie eine Krankenversicherung?" },
    { id: 16, answer: "Haben Sie in letzter Zeit Schwindelgefühle gehabt?" },
    { id: 17, answer: "Sind Sie schwanger?" },
    { id: 18, answer: "Rauchen Sie?" },
    { id: 19, answer: "Wie viele Zigaretten rauchen Sie pro Tag?" },
    { id: 20, answer: "Sind Sie nüchtern?" },
    { id: 21, answer: "Wann war Ihre letzte Blutuntersuchung?" },
    { id: 22, answer: "Hatten Sie schon einmal einen Herzinfarkt?" },
    { id: 23, answer: "Nehmen Sie Vitaminpräparate ein?" },
    { id: 24, answer: "Gibt es in Ihrer Familie Fälle von Diabetes?" },
    { id: 25, answer: "Haben Sie Brustschmerzen?" },
    { id: 26, answer: "Haben Sie Atembeschwerden?" },
    { id: 27, answer: "Seit wann haben Sie diese Schmerzen?" },
    { id: 28, answer: "Wie schätzen Sie Ihr Müdigkeitslevel ein?" },
    { id: 29, answer: "Leiden Sie an Schlaflosigkeit?" },
    { id: 30, answer: "Haben Sie eine Veränderung Ihres Appetits bemerkt?" },
  ],
  feel: [
    { id: 1, answer: "Mir geht es wunderbar." },
    { id: 2, answer: "Bist du glücklich?" },
    { id: 3, answer: "Hast du das tolle Wetter bemerkt?" },
    { id: 4, answer: "Warum bist du seit heute Morgen so eingeschnappt?" },
    { id: 5, answer: "Du hast mir gestern Abend gefehlt." },
    { id: 6, answer: "Hättest du Lust, am Wochenende auszugehen?" },
    { id: 7, answer: "Du siehst nicht gut aus. Ist alles in Ordnung?" },
    { id: 8, answer: "Denkst du immer noch an deine/n Ex?" },
    { id: 9, answer: "Hey, willst du eine Umarmung?" },
    { id: 10, answer: "Passiert es dir manchmal, einfach so zu weinen?" },
    { id: 11, answer: "Findest du nicht, dass das Leben heute wunderschön ist?" },
    { id: 12, answer: "Möchtest du über das reden, was dich bedrückt?" },
    { id: 13, answer: "Warum bist du so verlegen, wenn wir über Liebe sprechen?" },
    { id: 14, answer: "Wollen wir heute Abend zusammen essen gehen?" },
    { id: 15, answer: "Glaubst du an Liebe auf den ersten Blick?" },
    { id: 16, answer: "Wie gehst du normalerweise mit Wut um?" },
    { id: 17, answer: "Ich habe Angst, mein Leben zu verpassen. Geht es dir nicht auch so?" },
    { id: 18, answer: "Hättest du Lust, mit mir einen Kaffee trinken zu gehen?" },
    { id: 19, answer: "Hast du jemals diese große innere Leere gefühlt?" },
    { id: 20, answer: "Schläfst du in letzter Zeit gut?" },
    { id: 21, answer: "Hast du jemals daran gedacht, einfach abzuhauen und alles hinter dir zu lassen?" },
    { id: 22, answer: "Macht es dich nicht müde, überall gleichzeitig sein zu müssen?" },
    { id: 23, answer: "Bist du eher eifersüchtig?" },
    { id: 24, answer: "Warum hast du gestern so geschrien?" },
    { id: 25, answer: "Was hast du für deinen Urlaub geplant?" },
    { id: 26, answer: "Was hörst du für Musik, wenn du traurig bist?" },
    { id: 27, answer: "Willst du mit mir einen Film-Marathon machen?" },
    { id: 28, answer: "Was ist dein schlimmster Albtraum?" },
    { id: 29, answer: "Glaubst du, dass alles aus einem Grund passiert?" },
    { id: 30, answer: "Sag mal, was macht dich wirklich glücklich?" },
  ],
};
