// lang-sp.js
export const questAnswersSP = {
  qc: [
    { id: 1, answer: "No hay problema." },
    { id: 2, answer: "No puedo." },
    { id: 3, answer: "Estoy muy cansado." },
    { id: 4, answer: "Estoy bromeando." },
    { id: 5, answer: "Soy." },
    { id: 6, answer: "Escucha." },
    { id: 7, answer: "Escucha." },
    { id: 8, answer: "Y..." },
    { id: 9, answer: "Entonces / quiere decir" },
    { id: 10, answer: "Y más / además." },
  ],
  home: [
    { id: 1, answer: "¿Quieres beber algo?" },
    { id: 2, answer: "Pásame la mantequilla, por favor." },
    { id: 3, answer: "¿Dónde está el baño, por favor?" },
    { id: 4, answer: "¿Puedes cerrar la puerta, por favor?" },
    { id: 5, answer: "Pásame la sal, por favor." },
    { id: 6, answer: "¿Tienes hambre? ¡Vamos a comer!" },
    { id: 7, answer: "Dame un café, por favor." },
    { id: 8, answer: "¿Quieres un pequeño aperitivo?" },
    { id: 9, answer: "Apaga la luz, por favor." },
    { id: 10, answer: "Enciende la televisión, por favor." },
    { id: 11, answer: "Pásame la silla, por favor." },
    { id: 12, answer: "Cierra la ventana, por favor." },
    { id: 13, answer: "Limpia la mesa, por favor." },
    { id: 14, answer: "¿Quieres un trozo de pastel?" },
    { id: 15, answer: "Pásame un plato, por favor." },
    { id: 16, answer: "Pásame el pan, por favor." },
    { id: 17, answer: "¿Puedes ayudarme con los platos?" },
    { id: 18, answer: "¿Te gustaría ver una película?" },
    { id: 19, answer: "Ordena tu habitación, por favor." },
    { id: 20, answer: "Tómate tu abrigo, hace frío afuera." },
    { id: 21, answer: "Date prisa, por favor." },
    { id: 22, answer: "¿Quieres hacer una breve pausa?" },
    { id: 23, answer: "Confía en mí, por favor." },
    { id: 24, answer: "Acuéstate un momento, por favor." },
    { id: 25, answer: "¿Vienes a ayudarme en la cocina?" },
    { id: 26, answer: "Recuérdame cerrar la puerta." },
    { id: 27, answer: "Ten cuidado, por favor." },
    { id: 28, answer: "¿Quieres un café caliente?" },
    { id: 29, answer: "Toma tu paraguas, va a llover." },
    { id: 30, answer: "Dime la verdad, por favor." },
  ],
  med: [
    { id: 1, answer: "¿Cómo se siente hoy?" },
    { id: 2, answer: "¿Sintió algún dolor durante la noche?" },
    { id: 3, answer: "¿Dónde le duele?" },
    { id: 4, answer: "¿Está tomando medicamentos?" },
    { id: 5, answer: "¿Desde cuándo tiene estos síntomas?" },
    { id: 6, answer: "¿Tiene fiebre?" },
    { id: 7, answer: "¿Tiene alergias?" },
    { id: 8, answer: "¿Hace ejercicio regularmente?" },
    { id: 9, answer: "¿Durmió bien?" },
    { id: 10, answer: "¿Sufre de hipertensión?" },
    { id: 11, answer: "¿Cuándo fue su última cita médica?" },
    { id: 12, answer: "¿Ha tenido alguna cirugía?" },
    { id: 13, answer: "¿Puede describir su dolor?" },
    { id: 14, answer: "¿Cómo maneja el estrés?" },
    { id: 15, answer: "¿Tiene seguro médico?" },
    { id: 16, answer: "¿Ha sentido mareos recientemente?" },
    { id: 17, answer: "¿Está embarazada?" },
    { id: 18, answer: "¿Fuma?" },
    { id: 19, answer: "¿Cuántos cigarrillos fuma al día?" },
    { id: 20, answer: "¿Está en ayunas?" },
    { id: 21, answer: "¿Cuándo fue su último análisis de sangre?" },
    { id: 22, answer: "¿Ha sufrido un infarto?" },
    { id: 23, answer: "¿Toma suplementos vitamínicos?" },
    { id: 24, answer: "¿Hay antecedentes de diabetes en su familia?" },
    { id: 25, answer: "¿Tiene dolor en el pecho?" },
    { id: 26, answer: "¿Tiene dificultad para respirar?" },
    { id: 27, answer: "¿Desde cuándo tiene este dolor?" },
    { id: 28, answer: "¿Cómo calificaría su nivel de fatiga?" },
    { id: 29, answer: "¿Sufre de insomnio?" },
    { id: 30, answer: "¿Ha notado algún cambio en su apetito?" },
  ],
  feel: [
    { id: 1, answer: "Me siento de maravilla." },
    { id: 2, answer: "¿Eres feliz?" },
    { id: 3, answer: "¿Has notado el buen tiempo?" },
    { id: 4, answer: "¿Por qué estás de mal humor desde esta mañana?" },
    { id: 5, answer: "Te extrañé anoche." },
    { id: 6, answer: "¿Te apetece salir este fin de semana?" },
    { id: 7, answer: "No te ves bien. ¿Estás bien?" },
    { id: 8, answer: "¿Sigues pensando en tu ex?" },
    { id: 9, answer: "Oye, ¿quieres un abrazo?" },
    { id: 10, answer: "¿Te pasa a veces llorar sin razón?" },
    { id: 11, answer: "¿No crees que la vida es hermosa hoy?" },
    { id: 12, answer: "¿Te gustaría hablar sobre lo que te preocupa?" },
    { id: 13, answer: "¿Por qué te pones tan tímido cuando hablamos de amor?" },
    { id: 14, answer: "¿Salimos a cenar juntos esta noche?" },
    { id: 15, answer: "¿Crees en el amor a primera vista?" },
    { id: 16, answer: "¿Cómo sueles manejar la ira?" },
    { id: 17, answer: "Tengo miedo de perderme la vida. ¿No te pasa lo mismo?" },
    { id: 18, answer: "¿Te gustaría tomar un café conmigo?" },
    { id: 19, answer: "¿Alguna vez has sentido ese gran vacío interior?" },
    { id: 20, answer: "¿Has estado durmiendo bien últimamente?" },
    { id: 21, answer: "¿Alguna vez has pensado en simplemente huir y dejarlo todo atrás?" },
    { id: 22, answer: "¿No te cansa tener que estar en todas partes al mismo tiempo?" },
    { id: 23, answer: "¿Eres de los celosos?" },
    { id: 24, answer: "¿Por qué gritaste tanto ayer?" },
    { id: 25, answer: "¿Qué has planeado para tus vacaciones?" },
    { id: 26, answer: "¿Qué tipo de música escuchas cuando estás triste?" },
    { id: 27, answer: "¿Quieres hacer un maratón de películas conmigo?" },
    { id: 28, answer: "¿Cuál es tu peor pesadilla?" },
    { id: 29, answer: "¿Crees que todo sucede por una razón?" },
    { id: 30, answer: "Dime, ¿qué es lo que realmente te hace feliz?" },
  ],
};
