// lang-en.js
export const questAnswersEN = {
    qc: [
      { id: 1, answer: "No problem." },
      { id: 2, answer: "I can't." },
      { id: 3, answer: "I'm really tired." },
      { id: 4, answer: "I'm just kidding." },
      { id: 5, answer: "I am." },
      { id: 6, answer: "Listen up." },
      { id: 7, answer: "Listen up." },
      { id: 8, answer: "And..." },
      { id: 9, answer: "So / that means" },
      { id: 10, answer: "And more / besides." },
    ],
    home: [
      { id: 1, answer: "Would you like something to drink?" },
      { id: 2, answer: "Please pass me the butter." },
      { id: 3, answer: "Where is the restroom, please?" },
      { id: 4, answer: "Could you please close the door?" },
      { id: 5, answer: "Could you pass me the salt, please?" },
      { id: 6, answer: "Are you hungry? Let's eat!" },
      { id: 7, answer: "Please give me a coffee." },
      { id: 8, answer: "Would you like a little snack?" },
      { id: 9, answer: "Please turn off the light." },
      { id: 10, answer: "Please turn on the TV." },
      { id: 11, answer: "Please pass me the chair." },
      { id: 12, answer: "Please close the window." },
      { id: 13, answer: "Please clean the table." },
      { id: 14, answer: "Would you like a piece of cake?" },
      { id: 15, answer: "Please pass me a plate." },
      { id: 16, answer: "Please pass me the bread." },
      { id: 17, answer: "Can you help me with the dishes?" },
      { id: 18, answer: "Would you like to watch a movie?" },
      { id: 19, answer: "Please tidy up your room." },
      { id: 20, answer: "Take your coat, it's cold outside." },
      { id: 21, answer: "Please hurry up." },
      { id: 22, answer: "Would you like to take a short break?" },
      { id: 23, answer: "Trust me, please." },
      { id: 24, answer: "Please lie down for a moment." },
      { id: 25, answer: "Will you come help me in the kitchen?" },
      { id: 26, answer: "Remind me to close the door." },
      { id: 27, answer: "Please be careful." },
      { id: 28, answer: "Would you like a hot coffee?" },
      { id: 29, answer: "Take your umbrella, it's going to rain." },
      { id: 30, answer: "Please tell me the truth." },
    ],
    med: [
      { id: 1, answer: "How are you today?" },
      { id: 2, answer: "Did you experience any pain during the night?" },
      { id: 3, answer: "Where do you feel pain?" },
      { id: 4, answer: "Are you taking any medications?" },
      { id: 5, answer: "How long have you had these symptoms?" },
      { id: 6, answer: "Do you have a fever?" },
      { id: 7, answer: "Do you have any allergies?" },
      { id: 8, answer: "Do you exercise regularly?" },
      { id: 9, answer: "Did you sleep well?" },
      { id: 10, answer: "Do you suffer from high blood pressure?" },
      { id: 11, answer: "When was your last doctor appointment?" },
      { id: 12, answer: "Have you ever had surgery?" },
      { id: 13, answer: "Can you describe your pain?" },
      { id: 14, answer: "How do you handle stress?" },
      { id: 15, answer: "Do you have health insurance?" },
      { id: 16, answer: "Have you experienced dizziness recently?" },
      { id: 17, answer: "Are you pregnant?" },
      { id: 18, answer: "Do you smoke?" },
      { id: 19, answer: "How many cigarettes do you smoke per day?" },
      { id: 20, answer: "Are you fasting?" },
      { id: 21, answer: "When was your last blood test?" },
      { id: 22, answer: "Have you ever had a heart attack?" },
      { id: 23, answer: "Do you take vitamin supplements?" },
      { id: 24, answer: "Is there a history of diabetes in your family?" },
      { id: 25, answer: "Do you have chest pain?" },
      { id: 26, answer: "Do you have breathing difficulties?" },
      { id: 27, answer: "How long have you had this pain?" },
      { id: 28, answer: "How would you rate your level of fatigue?" },
      { id: 29, answer: "Do you suffer from insomnia?" },
      { id: 30, answer: "Have you noticed any change in your appetite?" },
    ],
    feel: [
      { id: 1, answer: "I'm doing wonderful." },
      { id: 2, answer: "Are you happy?" },
      { id: 3, answer: "Have you noticed the beautiful weather?" },
      { id: 4, answer: "Why have you been sulking since this morning?" },
      { id: 5, answer: "I missed you last night." },
      { id: 6, answer: "Would you like to go out this weekend?" },
      { id: 7, answer: "You don't look well. Is everything okay?" },
      { id: 8, answer: "Are you still thinking about your ex?" },
      { id: 9, answer: "Hey, do you want a hug?" },
      { id: 10, answer: "Does it ever happen that you cry for no reason?" },
      { id: 11, answer: "Don't you think life is beautiful today?" },
      { id: 12, answer: "Would you like to talk about what's bothering you?" },
      { id: 13, answer: "Why do you get so shy when we talk about love?" },
      { id: 14, answer: "Shall we go out for dinner tonight?" },
      { id: 15, answer: "Do you believe in love at first sight?" },
      { id: 16, answer: "How do you usually deal with anger?" },
      { id: 17, answer: "I'm afraid of missing out on life. Don't you feel the same?" },
      { id: 18, answer: "Would you like to grab a coffee with me?" },
      { id: 19, answer: "Have you ever felt that deep inner emptiness?" },
      { id: 20, answer: "Have you been sleeping well lately?" },
      { id: 21, answer: "Have you ever thought about just running away and leaving everything behind?" },
      { id: 22, answer: "Doesn't it tire you to be everywhere at once?" },
      { id: 23, answer: "Are you more jealous?" },
      { id: 24, answer: "Why did you scream so much yesterday?" },
      { id: 25, answer: "What have you planned for your vacation?" },
      { id: 26, answer: "What kind of music do you listen to when you're sad?" },
      { id: 27, answer: "Do you want to have a movie marathon with me?" },
      { id: 28, answer: "What is your worst nightmare?" },
      { id: 29, answer: "Do you believe everything happens for a reason?" },
      { id: 30, answer: "So, what really makes you happy?" },
    ],
    act: [
      { id: 1, answer: "I act correctly." },
      { id: 2, answer: "I bet that you will win." },
      { id: 3, answer: "I bet that I will lose." },
      { id: 4, answer: "I am cooking right now." },
      { id: 5, answer: "I'm coming!" },
      { id: 6, answer: "I am coming at 3 o’clock." },
      { id: 7, answer: "I will come back on Monday." },
      { id: 8, answer: "I am cooking right now." },
      { id: 9, answer: "I just cooked." },
      { id: 10, answer: "I have just arrived." },
      { id: 11, answer: "I understand that." },
      { id: 12, answer: "I don’t understand that." },
      { id: 13, answer: "I am driving to you." },
      { id: 14, answer: "I am going for a walk." },
      { id: 15, answer: "I am waiting for you." },
      { id: 16, answer: "I have had enough." },
      { id: 17, answer: "I am going swimming." },
      { id: 18, answer: "I am swimming in the pool." },
      { id: 19, answer: "I am sitting in the kitchen." },
      { id: 20, answer: "I am right." },
      { id: 21, answer: "I was wrong." },
      { id: 22, answer: "I got lost." },
      { id: 23, answer: "I am walking up the hill." },
      { id: 24, answer: "I am walking down the hill." },
      { id: 25, answer: "I am getting into the car." },
      { id: 26, answer: "I am getting on the bike." },
      { id: 27, answer: "I will say it only once." },
      { id: 28, answer: "I like this idea." },
      { id: 29, answer: "I don’t agree with you." },
      { id: 30, answer: "I am stopping now." },
  ],
  
  };
  